name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '1 8 * * *'
jobs:
  build-docker-images:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build rmf_demos image and push to gh registry
        run: |
          ./build-docker.sh
          docker push ghcr.io/open-rmf/rmf/rmf_demos
